In [15]:
import pandas as pd
import numpy as np

a = list()
b = [1, 2, 3, 4, 5]
c = [6, 6, 6, 6, 6]

b = np.array(b)
c = np.array(c)
t = np.vstack((b, c)).T
t

array([[1, 6],
       [2, 6],
       [3, 6],
       [4, 6],
       [5, 6]])

In [17]:
a = list()
b = [1, 2, 3, 4, 5]
c = [9, 9, 9, 9, 9]

b = np.array(b)
c = np.array(c)
q = np.vstack((b, c)).T
q

array([[1, 9],
       [2, 9],
       [3, 9],
       [4, 9],
       [5, 9]])

In [22]:
res = np.concatenate((t, q), axis=0)
res

array([[1, 6],
       [2, 6],
       [3, 6],
       [4, 6],
       [5, 6],
       [1, 9],
       [2, 9],
       [3, 9],
       [4, 9],
       [5, 9]])